SupplierQuality/SQA/urls.py
from . import views
from django.urls import path, include

app_name = 'SQA'
urlpatterns = [
    path('', views.SQAIndexView.as_view(), name='index'),
    path('suppliers/', include([
        path('', views.SupplierListView.as_view(), name='supplier_list'),
        path('<int:supplier_id>/', views.SupplierDetailView.as_view(), name='supplier_detail'),
    ])),
    path('parts/', include([
        path('', views.PartListView.as_view(), name='part_list'),
        path('<int:part_id>', views.PartDetailView.as_view(), name="part_detail")
    ])),
    path('claims/', include([
        path('', views.ClaimListView.as_view(), name='claim_list'),
        path('<int:claim_id>/', views.ClaimDetailView.as_view(), name='claim_detail')
    ])),
    path('ppap/', include([
        path('', views.PPAPListView.as_view(), name='ppap_list'),
        path('<int:ppap_id>/', views.PPAPDetailView.as_view(), name='ppap_detail')
    ])),

    #TESTING
    path('population-chart/', views.population_chart, name='population-chart'),
]

SupplierQuality/SupplierQuality/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SQA.urls', namespace='SQA')),
    path('accounts/', include('django.contrib.auth.urls')),
]

SupplierQuality/SQA/models.py
import datetime
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import CharField
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

    def __str__(self):
        return self.username


class Supplier_T1(models.Model):
    name = models.CharField(max_length=60, unique=True, default='Tier1 Supplier')
    valid_from = models.DateField(verbose_name='Supplier validated on', default=timezone.now)
    is_9001 = models.BooleanField(default=False)
    is_17494 = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Supplier_T2(models.Model):
    name = models.CharField(max_length=60, unique=True, default='Tier2 Supplier')
    supplier_t1 = models.ForeignKey(Supplier_T1, on_delete=CASCADE)

    def __str__(self):
        return self.name

class Supplier_T3(models.Model):
    name = models.CharField(max_length=60, unique=True, default='Tier3 Supplier')
    supplier_t1 = models.ForeignKey(Supplier_T1, on_delete=CASCADE)
    supplier_t2 = models.ForeignKey(Supplier_T2, on_delete=CASCADE)

    def __str__(self):
        return self.name

class Subassembly(models.Model):
    name = models.CharField(max_length=60, unique=True, default='Subassembly name')
    part_number = models.CharField(max_length=50)
    part_name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Part(models.Model):
    part_name = models.CharField(max_length=50, unique=True)
    part_number = models.CharField(max_length=30)
    subassy = models.ForeignKey(Subassembly, on_delete=CASCADE, default=None, null=True, blank=True)
    supplier_t1 = models.ForeignKey(Supplier_T1, on_delete=models.CASCADE)
    is_produced = models.BooleanField('Is in production' ,default=False)

    def __str__(self):
        return self.part_name


class Claim(models.Model):
    supplier_t1 = models.ForeignKey(
        Supplier_T1, on_delete=CASCADE)
    number = models.CharField(max_length=10, unique=True, blank=True)
    part_id =models.ForeignKey(
        Part, on_delete=CASCADE, default=1)
    supplier_number = models.CharField(blank=True, max_length=50)
    quantity = models.IntegerField(default=1)
    created = models.DateTimeField(verbose_name='Claim date', default=timezone.now)
    created_by = models.ForeignKey(
        User, on_delete=CASCADE)
    closed = models.BooleanField(default=False)
    closed_on = models.DateTimeField(verbose_name='Claim closed on', blank=True, null=True)
    D3_open = models.BooleanField(default=True)
    D3_closed_on = models.DateTimeField('D3 closed on', blank=True, null=True)
    D3_on_time = models.BooleanField(default=True)
    D6_open = models.BooleanField(default=True)
    D6_closed_on = models.DateTimeField('D6 closed on', blank=True, null=True)
    D6_on_time = models.BooleanField(default=True)
    D8_open = models.BooleanField(default=True)
    D8_closed_on = models.DateTimeField('D8 closed on', blank=True, null=True)
    D8_on_time = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        """
        Assigns claim number to Claim.number in the '8D YY/XXX' format
        """
        claims = Claim.objects.filter(created__year=self.created.year)
        post_count = claims.count() + 1
        self.number = f'8D {str(self.created.year)[2:4]}/{post_count:003}'
        super().save(*args, **kwargs)
        

    def set_due_dates(self):
        if self.closed == False:
            D3_date = self.created + timezone.timedelta.days(1)
            D6_date = self.created + timezone.timedelta.days(14)
            D8_date = self.created + timezone.timedelta(days=90)

            return {'D3': D3_date, 'D6': D6_date, 'D8': D8_date}

        return 'Claim is closed'

    def check_due_dates(self):
        duedates = self.set_due_dates()


# Make the claim status (or separate function) to update
# the "D3_open" and "D3_on_time" automaticly
# ALSO - validation error handling model.clean() method
# CHECK THIS IN THE DOCUMENTATION
# https://docs.djangoproject.com/en/3.2/ref/models/instances/

    def claim_status(self):
        duedate = self.set_due_dates()
        if self.D3_closed is None:
            if duedate.D3 < timezone.now() and self.D3_open == True:
                self.D3_on_time = False
            else:
                self.D3_on_time = True
        
        if self.D6_closed_on is None:
            if duedate.D6 < timezone.now() and self.D3_open == True:
                self.D6_on_time = False
            else:
                self.D6_on_time = True

        if self.D8_closed_on is None:
            if duedate.D8 < timezone.now() and self.D3_open == True:
                self.D8_on_time = False
            else:
                self.D8_on_time = True

        

    def __str__(self):
        return self.number


class PPAP(models.Model):
    part_id = models.ForeignKey(Part, on_delete=CASCADE, default=1)
    number = models.CharField(max_length=100, default='PPAP -supplier_name- -part_number- -revision- -date-')
    quantity = models.IntegerField(default=5)
    revision = models.CharField(max_length=20, default='0')
    validated = models.BooleanField(default=False)
    valid_from = models.DateField('validation date', null=True, blank=True)
    is_valid = models.BooleanField('Part is validated', default=False)

    def __str__(self):
        return self.number


#Make requalification class

SupplierQuality/SQA/forms.py
from typing_extensions import Required
from django import forms
from django.forms.widgets import Textarea
from .models import Supplier_T1

class Supplier_T1Form(forms.ModelForm):
    
    class Meta:
        model = Supplier_T1
        fields = ('name', 'address', 'valid_from', 'is_9001', 'is_17494')

SupplierQuality/SQA/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic.base import TemplateView
from django.db.models import Count
from .models import Claim, Supplier_T1, Part, PPAP
from django.views import View
from django.views.generic import ListView, DetailView, TemplateView
from django.http import JsonResponse
import json


class SQAIndexView(TemplateView):
    template_name = 'SQA/index.html'

    def get(self, request):
        query = self.get_queryset()


        return render(request, 'SQA/index.html', {
            'ppaps': query[0],
            'claims': query[1],
            })

    def get_queryset(self):
        ppaps = PPAP.objects.filter(validated=False)
        claims = Claim.objects.filter(closed=False)
        chart_data = Claim.objects.annotate(total=Count('supplier_t1')).order_by('supplier_t1')
        return [ppaps, claims, chart_data]


class SupplierListView(ListView):
    model = Supplier_T1
    template_name = 'SQA/supplier_list.html'

    def get_context_data(self, **kwargs):
        return {'suppliers': self.get_queryset()}


class SupplierDetailView(View):
    pk_url_kwarg = 'supplier_id'

    def get(self, request, supplier_id):
        print(supplier_id)
        return render(request, 'SQA/supplier_detail.html', {
            'suppliers': Supplier_T1.objects.all(),
            'supplier': self.get_queryset(supplier_id=supplier_id
            ), 'parts': self.get_queryset(parts=supplier_id
            ), 'claims': self.get_queryset(claims=supplier_id
            ), 'ppaps:': self.get_queryset(ppaps=supplier_id
            )})

    def get_queryset(self, supplier_id=None, parts=None, claims=None, ppaps=None):
        if supplier_id:
            return get_object_or_404(Supplier_T1, pk=supplier_id)
        if parts:
            return Part.objects.filter(supplier_t1=parts)
        if claims:
            return Claim.objects.filter(supplier_t1=claims)
        if ppaps:
            return PPAP.objects.filter(validated=True)

    #def get_context_data(self, **kwargs):
        """
        A DetailView can return ONLY ONE queryset
        Returned queryset can be accessed by "object" in HTML template
        The returned queryset contains data relevant only to pk
        pk is passed as "supplier.id" in the supplier_list.html
        """
        #return super().get_context_data(**kwargs)


class PartListView(ListView):
    model = Part
    template_name = 'SQA/part_list.html'

    def get_context_data(self, **kwargs):
        return {'parts': self.get_queryset().select_related() }


class PartDetailView(DetailView):
    model = Part
    template_name = 'SQA/part_detail.html'
    pk_url_kwarg = 'part_id'

    def get(self, request, part_id):
        return render(request, 'SQA/part_detail.html', {
            'ppaps': PPAP.objects.filter(part_id=part_id).all(),
            'parts': Part.objects.all(),
            'this_part': Part.objects.filter(pk=part_id)
        })


class ClaimListView(ListView):
    model = Claim
    template_name = 'SQA/claim_list.html'

    def get_context_data(self, **kwargs):
        return {'claims': self.get_queryset()}


class ClaimDetailView(DetailView):
    model = Claim
    template_name = 'SQA/claim_detail.html'
    pk_url_kwarg = 'claim_id'

    def get(self, request, claim_id):
        return render(request, 'SQA/claim_detail.html', {
            'claims': Claim.objects.all(),
            'claim': Claim.objects.filter(pk=claim_id)
        })


class PPAPListView(ListView):
    model = PPAP
    template_name = 'SQA/ppap_list.html'

    def get_context_data(self, **kwargs):
        return {'ppaps': self.get_queryset().select_related()}


class PPAPDetailView(DetailView):
    model = PPAP
    template_name = 'SQA/ppap_detail.html'
    pk_url_kwarg = 'ppap_id'


    def get(self, request, ppap_id):
        return render(request, 'SQA/ppap_detail.html', {
            'ppaps': PPAP.objects.all(),
            'ppap': PPAP.objects.filter(pk=ppap_id)
        })

# TESTING
def population_chart(request):
    supplier = []
    claim_total = []

    chart_data = Claim.objects.annotate(total=Count('supplier_t1')).order_by('supplier_t1').all()
    for dataset in chart_data:
        supplier.append(str(dataset.supplier_t1))
    
    supplier_set = set(supplier)
    for supplier_name in supplier_set:
        claim_total.append(supplier.count(supplier_name))
    supplier = list(supplier_set)
    print(supplier)
    print(claim_total)

    
    return JsonResponse(data={
        'labels': supplier,
        'data': claim_total,
    })

SupplierQuality/SQA/templates/SQA/base.html
{% load static %}
<!doctype html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title %}{% endblock title %}</title>
        {% block style %} {% endblock style %}
        <link rel="stylesheet" href="{% static 'dashboard.css' %}">
        <link rel="stylesheet" href="{% static 'navbar.css' %}">
        <link rel="stylesheet" href="https://use.typekit.net/vnx0pmk.css">
    </head>
    <body>
            <section class="navbar-container">
            {% include 'SQA/_navbar.html' %}
            </section>
            {% block content %}{% endblock content %}
    </body>
</html>

SupplierQuality/SQA/templates/SQA/charts.html
<!doctype html>
    <head>
    </head>
    <body>
    <div id="chartContainer" style="width: 400px;">
        <canvas id="population-chart" data-url="{% url 'SQA:population-chart' %}"></canvas>
    </div>

        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
        <script>

            $(function () {

            var $populationChart = $("#population-chart");
            $.ajax({
                url: $populationChart.data("url"),
                success: function (data) {

                var ctx = $populationChart[0].getContext("2d");

                new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                    labels: data.labels,
                    datasets: [{
                        label: 'Claim amount',
                        backgroundColor: ['blue', 'red', 'green'], 
                        data: data.data
                    }]          
                    },
                    options: {
                    responsive: true,
                    legend: {
                        position: 'left',
                    },
                    title: {
                        display: true,
                        text: 'Claim amount by supplier'
                    }
                    }
                });

                }
            });

            });

        </script>


    </body>
</html>

SupplierQuality/SQA/templates/SQA/claim_detail.html
{% extends 'SQA/base.html' %}


{% block title %} {{ object.name }} {% endblock title %}


{% block content %}
<div class="container">
    <div class="overview">
        <h1>Claim list</h1>
        <ul>
            {% for claim in claims %}
            <li><a href="{% url 'SQA:claim_detail' claim.id %}">{{ claim.number }}</a></li>
            {% empty %}
            </ul><h2>No pending claims</h2>
            {% endfor %}
        </ul>
    </div>

    <div class="details">
        <h1>Claim detail</h1>

        <h2>{{ claim.0.number }}</h2>
        {% if claim.0.closed %}
        <ul class="claim_open">
        {% else %}
        <ul class="claim_open">
        {% endif %}
            <li>{{ claim.0.supplier_t1 }}</li>
            <li>Date claimed: {{ claim.0.created }}</li>
            {% if claim.0.closed %}
            <li>Closed</li>
            {% else %}
            <li>Open</li>
            {% endif %}
        </ul>

{% endblock content %}

SupplierQuality/SQA/templates/SQA/claim_list.html
{% extends 'SQA/base.html' %}


{% block title %} Parts {% endblock title %}


{% block content %}
    <div class="container">
        <div class="overview">
            <h1> Claim list </h1>
            <ul>
                {% for claim in claims %}
                <li><a href="{% url 'SQA:claim_detail' claim.id %}">{{ claim.number }}</a></li>
                {% empty %}
                </ul><h2>No pending claims</h2>
                {% endfor %}
            </ul>
        </div>

        <div class="details">
            {% include 'SQA/charts.html' %}
        </div>
{% endblock content %}

SupplierQuality/SQA/templates/SQA/index.html
{% extends 'SQA/base.html' %}

{% block title %} Dashboard {% endblock title %}

{% block content %}
    <div class="container">
        <div class="overview">
            <h1> Dashboard </h1>
            <a href="{% url 'SQA:supplier_list' %}">Supplier list</a>
        </div>

        <div class="details">

        {% if claims %}
            <div class="charts">
            {% include 'SQA/charts.html' %}
            </div>
            
        {% endif %}
        <h2>Pending PPAP</h2>
        <hr>
        <table>
            <tr>
                <td>PPAP no.</td>
                <td>Part name</td>
                <td>Part number</td>
                <td>Part revision</td>
            </tr>
        {% for ppap in ppaps %}
            <tr>
                <td><a href="{% url 'SQA:ppap_detail' ppap.id %}">{{ ppap.number }}</a></td>
                <td>{{ ppap.part_id.part_name }}</td>
                <td>{{ ppap.part_id.part_number }}</td>
                <td>{{ ppap.revision }}</td>
            </tr>
        {% endfor %}
        </table>
        <br>

        <h2>Open claims</h2>
        <hr>
        <table>
            <tr>
                <td>Claim no.</td>
                <td>Supplier</td>
                <td>Part number</td>
                <td>Part name</td>
                <td>Quantity</td>
                <td>Opened on</td>
            </tr>
        {% for claim in claims %}
            <tr>
                <td><a href="{% url 'SQA:claim_detail' claim.id %}">{{ claim.number }}</a></td>
                <td>{{ claim.supplier_t1.name }}</td>
                <td>{{ claim.part_id.part_number }}</td>
                <td>{{ claim.part_id.part_name }}</td>
                <td>{{ claim.quantity }}</td>
                <td>{{ claim.created }}</td>
            </tr>
        {% endfor %}
        </table>
        </div>
    </div>
{% endblock content %}

SupplierQuality/SQA/templates/SQA/part_detail.html
{% extends 'SQA/base.html' %}


{% block title %} {{ object.name }} {% endblock title %}


{% block content %}
<div class="container">
    <div class="overview">
        <h1> Part list </h1>
        <ul>
            {% for part in parts %}
            <li><a href="{% url 'SQA:part_detail' part.id %}">{{ part.part_name }}</a></li>
            {% empty %}
            </ul><h2>No parts</h2>
            {% endfor %}
        </ul>
    </div>

    <div class="details">
        <h1>Part detail (part revision missing)</h1>
        <table>
            <tr>
                <td>Supplier</td>
                <td>Part name</td>
                <td>Part number</td>
                <td>Subassemlby</td>
                <td>In production</td>
            </tr>
            <tr>
                <td><a href="{% url 'SQA:supplier_detail' this_part.0.supplier_t1.id %}">{{ this_part.0.supplier_t1 }}</a></td>
                <td>{{ this_part.0.part_name }}</td>
                <td>{{ this_part.0.part_number }}</td>
                <td>{{ this_part.0.subassy }}</td>
                <td>{{ this_part.0.is_produced }}</td>
            </tr>
        </table>

        <h1>{{ ppap }}</h1>

        {% if ppaps %}
        <h2> Related PPAP </h2>
        <table>
            <tr>
                <td>PPAP no.</td>
                <td>Part revision</td>
                <td>Quantity</td>
                <td>Validated</td>
                <td>Valid from</td>
                <td>In production</td>
            </tr>
        {% for ppap in ppaps%}
            <tr>
                <td><a href="{% url 'SQA:ppap_detail' ppap.id %}">{{ ppap.number }}</a></td>
                <td>{{ ppap.revision }}</td>
                <td>{{ ppap.quantity }}</td>
                <td>
                    {% if ppap.validated %}
                    Yes
                    {% else %}
                    No
                    {% endif %}
                </td>
                <td>{{ ppap.valid_from }}</td>
                <td>{{ ppap.is_valid }}</td>
            </tr>
        {% endfor %}
        </table>
        {% else %}
        <h2> No PPAP available </h2>
        {% endif %}
    </div>
</div>

{% endblock content %}

SupplierQuality/SQA/templates/SQA/part_list.html
{% extends 'SQA/base.html' %}


{% block title %} Parts {% endblock title %}


{% block content %}
<div class="container">
    <div class="overview">
        <h1> Part list </h1>
        <ul>
            {% for part in parts %}
            <li><a href="{% url 'SQA:part_detail' part.id %}">{{ part.part_name }}</a></li>
            {% empty %}
            </ul><h2>No parts</h2>
            {% endfor %}
        </ul>
    </div>

    <div class="details">

    </div>
</div>
{% endblock content %}

SupplierQuality/SQA/templates/SQA/ppap_detail.html
{% extends 'SQA/base.html' %}


{% block title %} {{ object.name }} {% endblock title %}


{% block content %}
<div class="container">
    <div class="overview">
        <h1> PPAP list </h1>
        <ul>
            {% for ppap in ppaps %}
            <li><a href="{% url 'SQA:ppap_detail' ppap.id %}">{{ ppap.number }}</a></li>
            {% empty %}
            </ul><h2>No parts</h2>
            {% endfor %}
        </ul>
    </div>

    <div class="details">   
        <h1>PPAP detail</h1>

        <h2>{{ ppap.0.number }}</h2>
        <ul>
            <li><a href="{% url 'SQA:part_detail' ppap.0.part_id.id %}">{{ ppap.0.part_id.part_number }}</a></li>
            <li>{{ ppap.0.number }}</li>
            <li>{{ ppap.0.quantity }}</li>
            <li>{{ ppap.0.revision }}</li>
            <li>{{ ppap.0.valid_from }}</li>
            <li>{{ ppap.0.is_valid }}</li>
        </ul>
    </div>
</div>

{% endblock content %}

SupplierQuality/SQA/templates/SQA/ppap_list.html
{% extends 'SQA/base.html' %}


{% block title %} Parts {% endblock title %}


{% block content %}
<div class="container">
    <div class="overview">
        <h1> PPAP list </h1>
        <ul>
            {% for ppap in ppaps %}
            <li><a href="{% url 'SQA:ppap_detail' ppap.id %}">{{ ppap.number }}</a></li>
            {% empty %}
            </ul><h2>No pending ppap</h2>
            {% endfor %}
        </ul>
    </div>

    <div class="details">

    </div>
</div>
    <h1>{{ pp }}</h1>
{% endblock content %}

SupplierQuality/SQA/templates/SQA/supplier_detail.html
{% extends 'SQA/base.html' %}


{% block title %} {{ object.name }} {% endblock title %}


{% block content %}
<div class="container">
    <div class="overview">
        <h1> Supplier list </h1>
        <ul>
            {% for supplier in suppliers %}
            <li><a href="{% url 'SQA:supplier_detail' supplier.id %}">{{ supplier.name }}</a>
            {% empty %}
            </ul><h2>No suppliers</h2>
            {% endfor %}
        </ul>
    </div>

    <div class="details">

        <h1>Supplier detail</h1>

        <h2>{{ supplier.name }}</h2>
        <ul>
            {% if supplier.is_9001 %}<li> ISO 9001 </li>{% endif %}
            {% if supplier.is_17494 %}<li> ISO/IATF 17494 </li>{% endif %}
            {% if supplier.valid_from %}<li> Validated on: {{ supplier.valid_from }} </li>{% endif %}
        </ul>

        {% if parts %}
        <h2>Parts</h2>
        <ul>
            {% for part in parts %}
            <li><a href="{% url 'SQA:part_detail' part.id %}">{{ part.part_name }}</a></li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if claims %}
        <h2>Open claims</h2>
        <ul>
                {% for claim in claims %}
                {% if not claim.closed %}
                <li><a href="{% url 'SQA:claim_detail' claim.id %}">{{ claim.number }}</a></li>
                {% endif %}
                {% endfor %}
        </ul>
        {% endif %}

        {% if ppaps %}
        <h2>Open claims</h2>
        <ul>
                {% for claim in claims %}
                {% if not claim.closed %}
                <li><a href="{% url 'SQA:claim_detail' claim.id %}">{{ claim.number }}</a></li>
                {% endif %}
                {% endfor %}
        </ul>
    </div>
</div>
    {% endif %}
{% endblock content %}

SupplierQuality/SQA/templates/SQA/supplier_list.html
{% extends 'SQA/base.html' %}


{% block title %} Suppliers {% endblock title %}


{% block content %}
<div class="container">
    <div class="overview">
        <h1> Supplier list </h1>
        <ul>
            {% for supplier in suppliers %}
            <li><a href="{% url 'SQA:supplier_detail' supplier.id %}">{{ supplier.name }}</a>
            {% empty %}
            </ul><h2>No suppliers</h2>
            {% endfor %}
        </ul>
    </div>

    <div class="details">

    </div>
</div>
{% endblock content %}

SupplierQuality/SQA/templates/SQA/supplier_part_list.html
{% extends 'SQA/base.html' %}


{% block title %} {{ context }} {% endblock title %}


{% block content %}
    <h1>Supplier Part List</h1>

    <h2>{{ parts.supplier_t1 }}</h2>
    <ul>
        {% for part in parts %}
        <li>{{ part }}</li>
        {% endfor %}
    </ul>

{% endblock content %}